# This pipeline builds and deploy changes on dev or any feature branch and deploys it to DEV Cluster


trigger:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

name: $(Date:yyyy-MM-dd)$(Rev:.r)

variables:
  - group: dev-settings

pool:
  vmImage: ubuntu-20.04

stages:

  - stage: run_tests
    displayName: run tests
    jobs:
      - job:
        displayName: "run pytest"
        steps:
          - template: pipeline_templates/run_pytests.yml
            parameters:
              app_name: simple-api

  - stage: build_and_push
    displayName: build docker image
    jobs:
      - job: buildand_push_image
        displayName: build docker image
        steps:          
          - task: Docker@2
            inputs:
              containerRegistry: 'jgcarmonadev'
              repository: 'simple-api'
              command: 'buildAndPush'
              Dockerfile: 'simple-api/Dockerfile'